// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClSnuaqqEeL6AsUv_wiKpieElgl42p6go',
    appId: '1:400469711444:web:db8acd7c6a5a64a2d52bc1',
    messagingSenderId: '400469711444',
    projectId: 'flutterfire-ui-codelab-ef478',
    authDomain: 'flutterfire-ui-codelab-ef478.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ef478.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPJGFE0YhX71djJr1f1aQ2AAn_zS30_Q',
    appId: '1:400469711444:android:f875d537602c2e48d52bc1',
    messagingSenderId: '400469711444',
    projectId: 'flutterfire-ui-codelab-ef478',
    storageBucket: 'flutterfire-ui-codelab-ef478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7-0g9dHnQTSCTXfIZvICVIGnpJE_zB8',
    appId: '1:400469711444:ios:ad01e01514a28baad52bc1',
    messagingSenderId: '400469711444',
    projectId: 'flutterfire-ui-codelab-ef478',
    storageBucket: 'flutterfire-ui-codelab-ef478.appspot.com',
    iosClientId: '400469711444-7pr670s34girmlg32ogf5telasulf392.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP7-0g9dHnQTSCTXfIZvICVIGnpJE_zB8',
    appId: '1:400469711444:ios:9486bc78b13172a6d52bc1',
    messagingSenderId: '400469711444',
    projectId: 'flutterfire-ui-codelab-ef478',
    storageBucket: 'flutterfire-ui-codelab-ef478.appspot.com',
    iosClientId: '400469711444-h6crubtibtvo0i8uu55bfbtje5dhh3k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
